### ISSUE TITLE
Missing import

### ISSUE THREAD

**Issue by bartoszhernas** [payleven/mPOS-SDK-iOS#1]
Hey, you have missed to import 

    #import <PaylevenSDK/PLVPaymentResultAdditionalData.h>

in umbrela headers, so I had to import this by myself.
Especially usefull for Swift user, where now you have to import 

    #import <PaylevenSDK/PaylevenSDK.h>
    #import <PaylevenSDK/PLVPaymentResultAdditionalData.h>

both of them in Bridging Headers.

**Comment by konradfeketepayleven** [comment]
Hi,
Thank you for taking your time and providing us some feedback.
Very much appreciated!

We will definitely look into this and consider it for our next version.
Best regards
