### ISSUE TITLE
TImeout when connecting to device

### ISSUE THREAD

**Issue by bimusiek** [payleven/mPOS-SDK-iOS#3]
Hey guys,
I am getting this error:

```
Error Domain=Adyen Code=300 "Error communicating with the payment device" UserInfo={NSLocalizedDescription=Error communicating with the payment device, NSUnderlyingError=0x12e94d3c0 {Error Domain=BluetoothCommandErrorDomain Code=11001 "Timeout while waiting for message from device" UserInfo={NSLocalizedDescription=Timeout while waiting for message from device}}}
```

I am for sure correctly connected and everything, any idea what can be an issue?

**Comment by konradfeketepayleven** [comment]
Dear Michal,

This is a rare Bluetooth issue that is usually solved with a simple reboot/soft reset of the payment device.
In case the issue persists, please contact us directly by sending us a mail to developer@payleven.com and tell us the email address you are using for authentication/the payleven merchant account.
Best regards
